task:
  name: Build aarch64 Linux
  compute_engine_instance:
    image_project: cirrus-images
    image: family/docker-builder-arm64
    architecture: arm64
    platform: linux
    cpu: 8
    memory: 8G
  
  env:
    CIBW_BUILD: 'cp310-* pp37-* pp38-* pp39-*'
    CIBW_ARCHS: aarch64
    CIBW_ENVIRONMENT: 'PATH="$HOME/.cargo/bin:$PATH" CARGO_TERM_COLOR="always"'
    CIBW_BEFORE_BUILD_LINUX: >
      curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain=stable --profile=minimal -y &&
      rustup show
    CIBW_TEST_COMMAND: 'pytest {project}/test'
    CIBW_TEST_REQUIRES: pytest requests
    CIBW_BUILD_VERBOSITY: 1
    CIBW_CONTAINER_ENGINE: podman
  
  install_script:
    - apt update && apt install python3-venv python-is-python3 -y
    - pip install -U setuptools wheel cibuildwheel
  
  build_script:
    cibuildwheel --output-dir wheelhouse

  wheels_artifacts:
    path: "wheelhouse/*"
